### ISSUE TITLE
Process timeout on cp -R

### ISSUE THREAD

**Issue by Halama** [keboola/processor-move-files#3]
```
Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessTimedOutException: The process "cp -R /data/in/tables/pixel_fire.csv /data/out/tables/pixel_fire.csv" exceeded the timeout of 60 seconds. in /code/vendor/symfony/process/Process.php:1330
Stack trace:
#0 /code/vendor/symfony/process/Process.php(419): Symfony\Component\Process\Process->checkTimeout()
#1 /code/vendor/symfony/process/Process.php(214): Symfony\Component\Process\Process->wait()
#2 /code/vendor/symfony/process/Process.php(240): Symfony\Component\Process\Process->run(NULL, NULL)
#3 /code/main.php(96): Symfony\Component\Process\Process->mustRun()
#4 {main}
thrown in /code/vendor/symfony/process/Process.php on line 1330
```
https://keboola.zendesk.com/agent/tickets/7584

**Comment by Halama** [comment]
zaviram, spletl jsem se tyka se jineho procesoru
